Detect source encoding to properly interpret string literals
m-labs/pyparser pull request #17
Opened 2017-02-10 01:18 UTC by trotterdylan

This addresses https://github.com/m-labs/pythonparser/issues/6

Buffers now always hold unicode source, whereas before they could hold bytes if that's what were passed in to the constructor. This is possible because we determine the encoding and then use that to decode() the bytes. The side effect is that `Buffer.__init__` could raise UnicodeDecodeError if the input is badly encoded.

The Buffer encoding is then used by the lexer to produce a strdata token of the correct type for string literals. For unicode literals, escaping happens much as before via _replace_escape(). For bytes, there's a different code path that calls encode() using the Buffer's encoding followed by a special escaping function that ensures the value's not accidentally promoted to unicode.

The parser behavior for multi-string literals (e.g. `"foo" "bar"`) also had to change. When any of the literals are unicode, the result is unicode. When all the literals are bytes the resulting value is also bytes.

This PR also implements the unicode_literals future feature in a similar fashion to print_function. The one shortcoming of that approach is that it does not affect all string literals in the file, only the ones after the current lexer position. I think a proper implementation would require doing a lexer pass on the input to activate future flags before parsing. I didn't want to add any more complexity to this PR since it's already getting a bit big and this seems good enough for now.

2017-02-10 01:19 UTC, trotterdylan commented
Whoops looks like python3 is busted. Will fix.

2017-02-10 06:36 UTC, trotterdylan commented
The tests that parse string literals now use UnicodeOnly and BytesOnly values in the expected values to make sure both values and types are identical. Making this work for 2.x and 3.x grammars and run properly under 2.x and 3.x interpreters required some hackery.

PTAL

2017-02-10 14:55 UTC, whitequark requested changes
Some stylistic changes. Mostly the PR seems good; I'll look further at some of the conversions to see if they can perhaps be made cheaper, after that.

2017-02-10 14:55 UTC, whitequark commented on pythonparser/lexer.py
> -                chr = match.group(1)
What's the point of this change?

2017-02-10 14:55 UTC, whitequark commented on pythonparser/lexer.py
> -        is_raw     = ("r" in mode)
I prefer having these variables instead of poking into `mode`.

2017-02-10 15:55 UTC, trotterdylan commented on pythonparser/lexer.py
> -        is_raw     = ("r" in mode)
Done. Now is_unicode and is_byte are the inverse of each other so I've left out is_byte.

2017-02-10 15:55 UTC, trotterdylan commented on pythonparser/lexer.py
> -                chr = match.group(1)
Leftover from an older version where I had a chr() function.

2017-02-11 12:58 UTC, merged

2017-02-11 12:59 UTC, whitequark commented
By the way...

> This PR also implements the unicode_literals future feature in a similar fashion to print_function. The one shortcoming of that approach is that it does not affect all string literals in the file, only the ones after the current lexer position. I think a proper implementation would require doing a lexer pass on the input to activate future flags before parsing. I didn't want to add any more complexity to this PR since it's already getting a bit big and this seems good enough for now.

it's illegal to have any actual code before the future imports, so this is immaterial.

2017-02-11 16:16 UTC, trotterdylan commented
Thanks for merging!

The module docstring would be bytes whereas it should be unicode. Certainly unlikely to cause any problems but it is a material difference.

2017-02-11 16:57 UTC, whitequark commented
> The module docstring would be bytes whereas it should be unicode. Certainly unlikely to cause any problems but it is a material difference.

And only in Python 2 mode, right? That's fine by me, Python 2 support is only really included for completeness.

2017-02-11 17:20 UTC, trotterdylan commented
Right, Python 2 only. Also fine by me. Just making sure it's documented.